name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    
    runs-on: windows-2022

    steps:

      - name: Install
        env:
          NGROK_LINK: ${{ secrets.NGROK_LINK }}
         
        run: |
          powershell -Command "$env:NGROK_LINK"
           

      - name: Set up
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        
        run: |
          ngrok authtoken $env:NGROK_AUTH_TOKEN
          
      
      - name: Set up run
        env:
          
          NGROK_PORT: ${{ secrets.NGROK_PORT }}
          NGROK_PASS: ${{ secrets.NGROK_PASS }}
          NGROK_RUNN: ${{ secrets.NGROK_RUNN }}
        run: |
          powershell -Command "Set-LocalUser -Name 'runneradmin' -Password (ConvertTo-SecureString -AsPlainText 'Gurpreet@1414#&' -Force)"
          ngrok tcp $env:NGROK_PORT
        

        
      - name: Time
        run: sleep 21000
