name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    
    runs-on: windows-2022

    steps:

      - name: Install
        env:
          ANYDESK: ${{ secrets.ANYDESK }}
         
        run: |
          powershell -Command "$env:ANYDESK"
          powershell -Command "Invoke-WebRequest https://raw.githubusercontent.com/Gks908/WorkMode/main/start.bat -OutFile start.bat"


      - name: Run file
        run: start.bat
        

        
      - name: Time
        run: sleep 21000
