name: Win Workflow Run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      

      - name: Run Script
        env:
          CHOCO_INSTALL_ANYDESK: ${{ secrets.CHOCO_INSTALL_ANYDESK }}
          START_ANYDESK: ${{ secrets.START_ANYDESK }}
          PASS_ANYDESK: ${{ secrets.PASS_ANYDESK }}
          LOCATION_ANYDESK: ${{ secrets.LOCATION_ANYDESK }}
          
        shell: cmd
        run: |
          echo off
          powershell -Command "$env:CHOCO_INSTALL_ANYDESK"
          :$env:START_ANYDESK
          anydesk --start
          ping 127.0.0.1 -n 4 > nul
          
          for /f "delims=" %%i in ('"$env:LOCATION_ANYDESK" --get-id') do (
              set ID=%%i
          )
          
          if "%ID%"=="" (
              taskkill /f /im anydesk.exe > nul
              goto $env:START_ANYDESK
          )
          
          if "%ID%"=="0" (
              taskkill /f /im anydesk.exe > nul
              goto $env:START_ANYDESK
          )
          echo $env:PASS_ANYDESK | anydesk --set-password
          echo AnyDesk ID is: %ID%

      
        
      - name: Time
        run: sleep 21000
