name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:


      - name: Set up VNC Server

        run: |

          choco install -y tightvnc

          echo Gurpreet@1414 | vncpasswd -f > ~/.vnc/passwd

          vncserver :1 -geometry 1280x720

      
      - name: Install
        env:
          NGROK_LINK: ${{ secrets.NGROK_LINK }}
          POWERSHELL: ${{ secrets.POWERSHELL }}
        run: |
         powershell -Command "$env:NGROK_LINK"
         
      - name: Set up
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          RUNN: ${{ secrets.RUNN }}
          LOCAL_USER: ${{ secrets.LOCAL_USER }}
          NGROK_PASS: ${{ secrets.NGROK_PASS }}
          
        run: |
          ngrok authtoken $env:NGROK_AUTH_TOKEN
          
      - name: Set up run
        env:
          TCP: ${{ secrets.TCP }}
          NGROK_PORT: ${{ secrets.NGROK_PORT }}
        run: |
           ngrok $env:TCP $env:NGROK_PORT
      
      
        
      - name: Time
        run: sleep 21000
