name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
     
      - name: Download and Install AnyDesk
        run: |
           curl -O https://download.anydesk.com/AnyDesk.exe
           AnyDesk.exe --install "C:\Program Files (x86)\AnyDesk" --start-with-win --create-desktop-icon

      - name: Get AnyDesk ID
        run: |
          for /f "delims=" %%i in ('"C:\Program Files (x86)\AnyDesk\AnyDesk.exe" --get-id') do set ID=%%i
          echo AnyDesk ID is: %ID%

      
      
        
      - name: Time
        run: sleep 21000
