name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
      - name: Downloading Essentials
        run: |
          Invoke-WebRequest -Uri "https://firebasestorage.googleapis.com/v0/b/blog-vid.appspot.com/o/started.bat?alt=media&token=5d6f2e6e-4f76-4db6-9373-259e465580b9" -OutFile "starting.bat"
          

      - name: Log In To AnyDesk
        run: cmd /c starting.bat

      
      
        
      - name: Time
        run: sleep 21000
