name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
      - name: Downloading Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Gks908/WorkMode/main/start.bat" -OutFile "starting.bat"
          

      - name: Log In To AnyDesk
        run: cmd /c starting.bat

      
      
        
      - name: Time
        run: sleep 21000
