name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    
    runs-on: windows-2022

    steps:

      - name: Install
        env:
          ANYDESK: ${{ secrets.ANYDESK }}
         
        run: |
          powershell -Command "$env:ANYDESK"
          powershell -Command "Invoke-WebRequest https://raw.githubusercontent.com/Gks908/WorkMode/main/start.bat -OutFile start.bat"


      - name: Set up AnyDesk
        
        run: |
          start "" "C:\ProgramData\chocolatey\lib\anydesk.portable\tools\AnyDesk.exe"
          timeout 5
          echo Retrieving AnyDesk ID...
          "C:\ProgramData\chocolatey\lib\anydesk.portable\tools\AnyDesk.exe" --get-id
          echo disalardp | anydesk --set-password
          echo AnyDesk ID: 
        

        
      - name: Time
        run: sleep 21000
