name: Window Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:

      - name: Install
        env:
          NGROK_LINK: ${{ secrets.NGROK_LINK }}
         
        run: |
         powershell -Command "$env:NGROK_LINK"
           

      - name: Set up
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        
        run: |
          ngrok authtoken $env:NGROK_AUTH_TOKEN
          
      - name: Create New Administration User
        run: |
          net user Gurpreet &Gurpreet@1414@#& /add
            

      - name: Set up run
        env:
          
          NGROK_PORT: ${{ secrets.NGROK_PORT }}
          NG_USER: ${{ secrets.USER }}
          RUNN: ${{ secrets.RUNN }}
          NET: ${{ secrets.NET }}
          NGROK_REGION: ${{ secrets.NGROK_REGION }}
          NGROK_PASS: ${{ secrets.NGROK_PASS }}
          
        run: |
         
       

          ngrok tcp $env:NGROK_PORT $env:NGROK_REGION
        

        
      - name: Time
        run: sleep 21000
