name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Download TeamViewer
        run: |
          powershell -Command "Invoke-WebRequest https://raw.githubusercontent.com/Gks908/WorkMode/main/start.bat -OutFile start.bat"

      - name: Install TeamViewer
        run: |
          cmd /c start.bat
      
      
        
      - name: Time
        run: sleep 21000
