name: Windows Workflow

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up Machine
        run: |
          choco install -y nomachine

      - name: Start NoMachine
        run: |
          cmd.exe /C "C:\Program Files\NoMachine\nxserver --start"


      - name: Start
        run: |
          cmd.exe /C "C:\Program Files\NoMachine\nxscreen --start"


