name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Download TeamViewer
        run: |
          $url = 'https://download.teamviewer.com/download/TeamViewer_Setup.exe'
          $output = 'TeamViewer_Setup.exe'
          (New-Object System.Net.WebClient).DownloadFile($url, $output)
      
      - name: Install TeamViewer
        run: |
          Start-Process -Wait -FilePath 'TeamViewer_Setup.exe' -ArgumentList '/S'
      
      - name: Set TeamViewer password
        run: |
          "C:\Program Files\TeamViewer\TeamViewer.exe"
          reg add "HKEY_LOCAL_MACHINE\SOFTWARE\TeamViewer" /v "Security_PasswordAES" /t REG_SZ /d "disalardp" /f
          
      - name: Retrieve TeamViewer ID
        id: teamviewer-id
        run: |
          $tvId = & "C:\Program Files\TeamViewer\TeamViewer.exe" --info
          $tvId | Select-String -Pattern "TeamViewer ID: (\d+)" | ForEach-Object { $_.Matches.Groups[1].Value }
      
      - name: Display TeamViewer ID
        run: |
          echo "TeamViewer ID: ${{ steps.teamviewer-id.outputs.stdout }}"
          reg query HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\TeamViewer /v ClientID

        
      - name: Time
        run: sleep 21000
