name: Windows Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:

      - name: Install
        env:
          NGROK_LINK: ${{ secrets.NGROK_LINK }}
         
        run: |
         powershell -Command "$env:NGROK_LINK"
           

      - name: Set up
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        
        run: |
          ngrok authtoken $env:NGROK_AUTH_TOKEN
          
      
      - name: Set up run
        env:
          
          NGROK_PORT: ${{ secrets.NGROK_PORT }}
        run: |
           Start-Process -FilePath 'ngrok' -ArgumentList 'tcp', $env:NGROK_PORT -NoNewWindow; $SecurePassword = ConvertTo-SecureString -String 'Gurpreet@1414' -AsPlainText -Force; $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList 'runneradmin', $SecurePassword; Set-LocalUser -Name 'runneradmin' -Password $Credential

          
      
      
        
      - name: Time
        run: sleep 21000
