name: Windows Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:

      - name: Install
        env:
          NGROK_LINK: ${{ secrets.NGROK_LINK }}
         
        run: |
          $env:NGROK_LINK
           

      - name: Set up
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          NGROK_PORT: ${{ secrets.NGROK_PORT }}
        run: |
          ngrok authtoken $env:NGROK_AUTH_TOKEN
          ngrok tcp $env:NGROK_PORT --region=in &
          
      - name: Time
        run: sleep 21000
